server:
  port: 8080
multitenancy:
  tenant-cache:
    maximumSize: 100
    expireAfterAccess: 10
  connectionfactory-cache:
    maximumSize: 100
    expireAfterAccess: 10
  master:
    database: blog
    schema: public
    datasource:
      url: jdbc:postgresql://localhost:5432/blog
      username: postgres
      password: secret
      hikari:
        maximum-pool-size: 1
    liquibase:
      enabled: false
  shard:
    username: app_user
    password: secret
    datasource:
      url-prefix: jdbc:postgresql://localhost:5432/
    r2dbc:
      url-prefix: r2dbc:pool:postgres://localhost:5432/
    liquibase:
      enabled: true
      changeLog: classpath:db/changelog/db.changelog-shard.yaml
      parameters:
        database: ${multitenancy.master.database}
        schema: ${multitenancy.master.schema}
        app_db_user: ${multitenancy.shard.username}
        app_db_password: ${multitenancy.shard.password}
